language: perl
env:
  - OS=ubuntu JDKVER=jdk7 GROUP=test
perl:
  - "5.24"
jdk:
  - openjdk7
install:
  - jdk_switcher use openjdk7
  - (echo y;echo o conf prerequisites_policy follow;echo o conf commit) | cpan
  - cpan install Carton
  - carton install
  - ./init.sh
script:
  - cd framework/test
  - carton exec ./test_tutorial.sh
