sudo: false
language: java
jdk: openjdk7
perl:
  - "5.24"
install:
  - echo y | cpan
  - cpan install Carton
  - carton install
  - ./init.sh
script:
  - echo $(java -version)
  - cd framework/test
  - carton exec ./test_tutorial.sh
