language: perl
sudo: enabled
env:
  - OS=ubuntu JDKVER=jdk7 GROUP=test
perl:
  - "5.24"
install:
  - (echo y;echo o conf prerequisites_policy follow;echo o conf commit)|cpan
  - cpan install Carton
  - carton install
  - sudo ./init.sh
script:
  - cd framework/test
  - ./test_tutorial.sh
